# Generated by Django 3.1.6 on 2021-02-11 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Guitar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=250)),
                ('model', models.CharField(max_length=250)),
                ('serial', models.CharField(max_length=250)),
                ('year', models.IntegerField()),
                ('description', models.TextField(max_length=250)),
            ],
        ),
    ]
