# Generated by Django 3.1.6 on 2021-02-16 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case', models.CharField(choices=[('hardshell', 'HARDSHELL'), ('gig bag', 'GIG BAG')], default='hardshell', max_length=50)),
                ('brand', models.CharField(max_length=100)),
            ],
        ),
    ]
