# Generated by Django 3.1.6 on 2021-02-17 19:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_case'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='case',
            field=models.CharField(max_length=50),
        ),
        migrations.CreateModel(
            name='Practice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.CharField(choices=[('20', '20 minutes'), ('30', '30 minutes'), ('45', '45 minutes'), ('60', '60 minutes')], default='20', max_length=2)),
                ('focus', models.CharField(choices=[('THEORY', 'Theory'), ('SCALES', 'Scales'), ('ARPEGGIOS', 'Arpeggios'), ('CHORDS', 'Chords'), ('COMPOSITION', 'Composition')], default='Theory', max_length=50)),
                ('guitar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.guitar')),
            ],
        ),
    ]
