# Generated by Django 3.1.6 on 2021-02-17 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20210217_1309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='practice',
            name='date',
            field=models.DateField(verbose_name='Practice Date'),
        ),
        migrations.AlterField(
            model_name='practice',
            name='focus',
            field=models.CharField(choices=[('THEORY', 'Theory'), ('SCALES', 'Scales'), ('ARPEGGIOS', 'Arpeggios'), ('CHORDS', 'Chords'), ('COMPOSITION', 'Composition')], default='THEORY', max_length=50),
        ),
    ]
